### ISSUE TITLE
Error while compilation

### ISSUE THREAD

**Issue by adrienbuffet** [kaihenzler/node-mcp23017#2]
Hi, 
i'm getting an error at compilation with > node-gyp rebuild

Can you help ?

i2c.target.mk:90: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory '/home/pi/nodeserver/node_modules/i2c/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/nodeserver/node_modules/i2c
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/nodeserver/package.json'
npm WARN nodeserver No description
npm WARN nodeserver No repository field.
npm WARN nodeserver No README data
npm WARN nodeserver No license field.
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-mcp23017" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! i2c@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c@0.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the i2c package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs i2c
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls i2c
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/nodeserver/npm-debug.log

[npm-debug.log.txt](https://github.com/kaihenzler/node-mcp23017/files/825924/npm-debug.log.txt)

**Comment by pinger** [comment]
There is problem with old version "i2c" in decencies - "i2c": "0.1.4".
Try clone the repo, edit - e.g. -> "i2c": "0.2.3"
Install the module from local source - npm install /home/pi/src/node-mcp23017/ --save

**Comment by adrienbuffet** [comment]
Thanks for help dude :D

 

Cordialement

 

Adrien Charles BUFFET

Etudiant M.Sc 1 Nice

 

SUPINFO International University

21-boulevard François Grosso – 06000 Nice – France

+33 1 53 35 97 00

 

SUPINFO, Sign of Success®

Follow us :  <http://www.facebook.com/supinfo> Faceboo <http://www.facebook.com/supinfo> k |  <http://www.twitter.com/supinfo> Twitte <http://www.twitter.com/supinfo> r |  <http://www.youtube.com/supinfomovie> Youtube

 

De : pinger [mailto:notifications@github.com] 
Envoyé : vendredi 10 mars 2017 12:01
À : kaihenzler/node-mcp23017 <node-mcp23017@noreply.github.com>
Cc : Adrien Buffet <contact@theitguy.fr>; Author <author@noreply.github.com>
Objet : Re: [kaihenzler/node-mcp23017] Error while compilation (#2)

 

There is problem with old version "i2c" in decencies - "i2c": "0.1.4".
Try clone the repo, edit - e.g. -> "i2c": "0.2.3"
Install the module from local source - npm install /home/pi/src/node-mcp23017/ --save

**Comment by adrienbuffet** [comment]
Hi, thanks for help.

 

I’m having a problem with reading digital values. Can you help me ?

 

I’ve got a yl-69 soil moisture connected to the mcp, as the led on it lit, it’s sending a digital « true » signal to the mcp…

When i’m using the digitalRead function as described in your example code, i’m getting this : 

 



 



 

 

It seems to be random.

Any ideas ?

 

Thanks.

 

 

De : pinger [mailto:notifications@github.com] 
Envoyé : vendredi 10 mars 2017 12:01
À : kaihenzler/node-mcp23017 <node-mcp23017@noreply.github.com>
Cc : Adrien Buffet <contact@theitguy.fr>; Author <author@noreply.github.com>
Objet : Re: [kaihenzler/node-mcp23017] Error while compilation (#2)

 

There is problem with old version "i2c" in decencies - "i2c": "0.1.4".
Try clone the repo, edit - e.g. -> "i2c": "0.2.3"
Install the module from local source - npm install /home/pi/src/node-mcp23017/ --save

**Comment by kaihenzler** [comment]
I guess you are not compiling this on a linux based OS. The problem comes from the dependency to the i2c module. There is an open issue in the i2c module.
https://github.com/kelly/node-i2c/issues/17

I don't know how to resolve this to make this package work on any other OS than Linux

**Comment by asknaskan** [comment]
This one seems to be solved for this repo with #3.

**Comment by asknaskan** [comment]
You are right, it can not be installed on an OSX device.
Do you plan to add any cross-platform compatibility?

Anyway, it reads for me that this issue seems to have something to do with version incompatiblity when installing on an raspberry and not an cross-platform issue; Line`npm ERR! /home/pi/nodeserver/npm-debug.log` shows that it seems to run on an raspberry - also, take a look at https://github.com/kelly/node-i2c/issues/75. Thats why I thought it could be closed.

**Comment by kaihenzler** [comment]
@asknaskan you are totally right. I didn't analyse the following log completely `npm ERR! /home/pi/nodeserver/npm-debug.log`, because the OSX error looks very similar 🤦‍♂️ 

@adrienbuffet have you tried compiling this with node greater or equal than 8?

**Comment by vlturner** [comment]
i2c is updated to 0.5.5 and been talking with the developer. There are problems with lots of the i2c stuff being out of sync. I have node-red-contrib-i2c installing and see its notes. Now I need to get my NCD 32-Channel High-Power Relay Controller with I2C Interface based on mcp23017 working.

There are issues with GIT and NPM versions out of sync too.
